language: C++
sudo: enabled
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-6
      - cmake
      - libeigen3-dev
script:
  - find /usr/ -name Eigen3Config.cmake
  - mkdir .sim_build && cd .sim_build && cmake .. && make
  - mkdir .real_build && cd .real_build && cmake .. -DREAL=ON && make

