language: C++
sudo: enabled
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-6
      - cmake
      - libeigen3-dev
before_install:
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
script:
  - cmake --version
  - mkdir .sim_build && cd .sim_build && cmake .. -DCMAKE_MODULE_PATH=/usr/share/cmake-2.8/ && make
  - mkdir .real_build && cd .real_build && cmake .. -DCMAKE_MODULE_PATH=/usr/share/cmake-2.8/ -DREAL=ON && make

